#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Sep 23 21:10:39 CST 2026
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto e5abda5f0131475287e477b25e789f91 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot cnn_top_tb_func_impl xil_defaultlib.cnn_top_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto e5abda5f0131475287e477b25e789f91 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot cnn_top_tb_func_impl xil_defaultlib.cnn_top_tb xil_defaultlib.glbl -log elaborate.log

