# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /mnt/hgfs/Digital_Shared_Folder/Best_design_v2_compare/LAST_VERISON/project_9/project_9.cache/wt [current_project]
set_property parent.project_path /mnt/hgfs/Digital_Shared_Folder/Best_design_v2_compare/LAST_VERISON/project_9/project_9.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /mnt/hgfs/Digital_Shared_Folder/Best_design_v2_compare/LAST_VERISON/project_9/project_9.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /mnt/hgfs/Digital_Shared_Folder/Best_design_v2_compare/LAST_VERISON/rtl/cnn_controller.v
  /mnt/hgfs/Digital_Shared_Folder/Best_design_v2_compare/LAST_VERISON/rtl/kernel_coeff_memory.v
  /mnt/hgfs/Digital_Shared_Folder/Best_design_v2_compare/LAST_VERISON/rtl/line_buffer.v
  /mnt/hgfs/Digital_Shared_Folder/Best_design_v2_compare/LAST_VERISON/rtl/output_stage.v
  /mnt/hgfs/Digital_Shared_Folder/Best_design_v2_compare/LAST_VERISON/rtl/tree_nxn.v
  /mnt/hgfs/Digital_Shared_Folder/Best_design_v2_compare/LAST_VERISON/rtl/window_nxn.v
  /mnt/hgfs/Digital_Shared_Folder/Best_design_v2_compare/LAST_VERISON/rtl/cnn_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /mnt/hgfs/Digital_Shared_Folder/Best_design_v2_compare/LAST_VERISON/project_9/project_9.srcs/constrs_2/new/synth_constraints.xdc
set_property used_in_implementation false [get_files /mnt/hgfs/Digital_Shared_Folder/Best_design_v2_compare/LAST_VERISON/project_9/project_9.srcs/constrs_2/new/synth_constraints.xdc]

read_xdc /mnt/hgfs/Digital_Shared_Folder/Best_design_v2_compare/LAST_VERISON/project_9/project_9.srcs/constrs_2/new/waiver_messages.xdc
set_property used_in_implementation false [get_files /mnt/hgfs/Digital_Shared_Folder/Best_design_v2_compare/LAST_VERISON/project_9/project_9.srcs/constrs_2/new/waiver_messages.xdc]

read_xdc /mnt/hgfs/Digital_Shared_Folder/Best_design_v2_compare/LAST_VERISON/constraints/pblock.xdc
set_property used_in_implementation false [get_files /mnt/hgfs/Digital_Shared_Folder/Best_design_v2_compare/LAST_VERISON/constraints/pblock.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cnn_top -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cnn_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cnn_top_utilization_synth.rpt -pb cnn_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
